### PR TITLE
Fixed QFileDialog instantiation. Fixes pgmodeler/pgmodeler#702

### PR DESCRIPTION
**Pull request by nickguletskii**

### CODE REVIEW

**Comment by nickguletskii** [comment]
Apologies for the broken indentation. You should probably set up automatic formatting because the formatting seems to be inconsistent throughout the project...

**Comment by rkhaotix** [comment]
No problem. I really use automatic formatting.

**Comment by nickguletskii** [comment]
I'll have a look at it in a moment.

**Comment by rkhaotix** [comment]
You can replace the results_tbw by qApp->activeWindow()

**Comment by nickguletskii** [comment]
Isn't that a bit hackish? After all, results_tbw makes more sense as a parent.

Does having results_tbw as the parent really cause any issues? If it does, I'll add a commit that changes it to qApp->activeWindow().

**Comment by rkhaotix** [comment]
Oh man, sorry. Commented in the wrong line.
If we setup a parent for SQLExecutionWidget::sql_file_dlg as "this" the result will be:

qfiledialog

And I think the result will be the same if we set the parent as "results_tbw" in SQLExecutionWidget::exportResults

**Comment by nickguletskii** [comment]
Yeah, passing parent to sql_file_dlg results in the same problem as not setting the parent at all for me (must have missed this dialog when testing).

If the screenshot you posted occurs when you pass this to sql_file_dlg, then I am not really sure what to do...

**Comment by rkhaotix** [comment]
If you are really sure that the dialog hanging is caused by the absence of a parent then using qApp->activeWindow() should solve. At least this is the only solution I can see right now.

**Comment by nickguletskii** [comment]
I added the commit that uses `qApp->activeWindow()`, but it's still a hack. I will create an issue tomorrow to make sure that any issues that arise from this can be tracked down back to this commit. I will also try experimenting with QFileDialogs outside of pgmodeler and report my results to Qt devs, because it's either an issue with Qt, their documentation, KDE or something very obscure with pgmodeler.

**Comment by nickguletskii** [comment]
Oh damn, after searching a little more thoroughly, I found this: https://www.kde.org/announcements/kde-frameworks-5.10.0.php

Basically, it's an issue with KDE frameworks. I am not sure if it's worth merging this now.

**Comment by rkhaotix** [comment]
Hmmm. I was suspecting that could be an issue with Kde :)
Anyway i'll let the pull request here if you confirm something else we can
drop it. Thanks!
Em 01/07/2015 18:17, "Nick Guletskii" <notifications@github.com> escreveu:

**Pull request closed without merging**
