### PR TITLE
Multidimensional layers

### PR DESCRIPTION
**Pull request by Maxzor**
Hello,
A note about multidimensional layers :
I have represented dimensions with qtreewidgets rather than qlistwidgets to allow for nesting layers in a dimension. Currently I see the cost of allowing nesting higher than the value it would bring, but this can be done next.

### CODE REVIEW

**Comment by Maxzor** [comment]
A bit of the why :)
This is near what I would like schemas in RDBMS implementations to be.
A table could be in several schemas... It could accessed from various ways, access-right management would be so much better, and a long list of other pros.
Maybe one day **real** multidimensional design tools will take off, I would love to explore visually 3D space instead of a flat surface.

For this feature, it allows to categorize information in an unlimited amount of dimensions. And you can then filter visually cross-dimension which I found pretty cool.

**Comment by Maxzor** [comment]
The implementation in itself is somewhat dirty, especially function names which would benefit from a rework.

**Comment by rkhaotix** [comment]
Don't worry about functions names and other details of your implementation. I'll study it and improve where I think is necessary. The idea here is more important than the implementation. The latter is just a matter is taste :)

**Comment by Maxzor** [comment]
Had a trial at "production" today and found some bugs. Force pushed 96a0ce3

**Comment by Maxzor** [comment]
Self-explaining bugfix.

**Comment by Maxzor** [comment]
Found yet another bug... force-pushed a wannabe-clean squash

**Comment by Maxzor** [comment]
Any news on this front?

**Comment by rkhaotix** [comment]
Hi @Maxzor 

I'll add this to the development of 0.9.3. Right now I'm working only on bug fixes in order to release 0.9.2 until the end of December.

**Pull request closed without merging**
