### PR TITLE
Add CodeOption to Split File Script Export.  Allow create all scripts with Children.

### PR DESCRIPTION
**Pull request by dpomerantz-jci**
Adding Code option as a Command Line option seems to work.  I tested several scenarios.  There are plenty of opportunities for code reuse, and I encourage that, but I needed something that would with minimal effort.  Please let me know if you will or will not merge this into your main product and release a hotfix.  If it's not going to happen, I need to know so that I can create custom builds for our developers.

### CODE REVIEW

**Comment by rkhaotix** [comment]
Hey, @dpomerantz-jci 

Thanks for that. Of course, I can merge it. I'll try merging it on a branch based on 1.0.0-beta code and test it. If everything is okay I will then merge it to develop branch.

**Comment by dpomerantz-jci** [comment]
Is there any way that you will be able and willing to release a new build which includes this change and is based on 0.9.4?  Maybe 0.9.4a or 0.9.4.1?  I don't know that we're ready to move up to the 1.0 release, and would like to just get this feature added.  I branched from the released version of 0.9.4 to facilitate that.  Thanks!

**Comment by rkhaotix** [comment]
I can create a snapshot build based on the PR.

**Comment by dpomerantz-jci** [comment]
> I can create a snapshot build based on the PR.

Awesome, thank you!

**Comment by rkhaotix** [comment]
@dpomerantz-jci Since I moved on to the development of 1.0.0, I don't plan to keep working on 0.9.4. But your PR is a good idea and can help me to add an expanded version of the feature (see #1697) in 1.0.0, so the idea of the snapshot build is to solve your problem immediately but it would not be merged into the ```main``` branch, instead, I will improve the solution (removing some code duplications and adding some polishing that I imagined in a first glance) and apply it only in the development branch (1.0.0-alpha1, currently).

P.S.: I would recommend you try moving to 1.0.0 as soon as the beta or beta1 is out because a lot of things changed and you may face some compatibility issues that may demand some manual fixes. Anyway, I'll be here to help you in the transition.

**Comment by dpomerantz-jci** [comment]
That makes sense and sounds like the best of both worlds.  Thank you.  I was able to build a Win32 snapshot, but Win64 won't build, and I have to reach out to someone else to build for mac.  Please let me know when those snapshots are available, and I can download.

**Comment by rkhaotix** [comment]
Great! I'll try to build the snapshots on Monday but first I will need to configure a Qt5- only environment on Windows and macOs. I'll let you know when the builds are ready.

**Comment by rkhaotix** [comment]
@dpomerantz-jci The snapshot build is ready. You can get the binaries on the site. I've tested on Linux and Windows and they seem ok. The macOS version I just compiled and uploaded, but you can call me if something is wrong, ok?

**Comment by dpomerantz-jci** [comment]
@rkhaotix Thank you.  I will start using the Win64 version immediately and will disseminate the MacOS version to my colleagues.  I'll reach out if there are any issues.

**Pull request merged**
