### PR TITLE
Allow pgmodeler to be compiled with Visual Studio

### PR DESCRIPTION
**Pull request by lowjoel**
Hello there,

I'm not sure whether you guys are interested in this, but this PR will allow compiling of pgmodeler on Windows. I've made the changes such that other platforms _should not_ be affected (though I can't guarantee it)

I built this using Qt Creator, Qt 5.3, MSVC 2013 x64, with my own libxml2, and the Windows 64-bit PostgreSQL distribution (EnterpriseDB) libpq.dll

Let me know if you need anything.

There are some places in the code which will trigger a debug check on VC -- see the last 2 or 3 commits of this PR. There might be other places, I'll fix them and PR when I encounter them.

### CODE REVIEW

**Comment by rkhaotix** [comment]
Congratulations @lowjoel!
This is such a huge work, but unfortunately the compilation fails for clang (my default compiler in Linux and Mac OSX). Not tested for gcc yet.

lowjoel

Maybe we can create a parallel branch like pgmodeler-visualstudio? I think it can be safer than just merge your changes in the official pgModeler's codebase.

**Comment by lowjoel** [comment]
Maybe I didn't modify the .pro file properly... on all platforms except Windows, LIBXXX_EXPORT is supposed to be defined to nothing (so it compiles the same as before)

Can you have a look?

**Comment by rkhaotix** [comment]
Yes, they seem to be defined in pgmodeler.pri

lowjoel1

**Comment by lowjoel** [comment]
Have you tried running qmake again? (I'm sorry if this sounds stupid...)

**Comment by rkhaotix** [comment]
Yep. :)

**Comment by lowjoel** [comment]
I'll find a way to compile this on Linux then. I'll update this PR when I do manage to get this to work.

**Comment by rkhaotix** [comment]
Ok! :+1:

**Comment by lowjoel** [comment]
@rkhaotix Fixed. I compiled using clang 3.5, Qt 5.3, Kubuntu 14.10.

**Comment by rkhaotix** [comment]
Cool! I tested it too and it works!
The only thing I not like is the fact that we need to remove some C++11 features like "constexpr" usage because the lack of support from Visual Studio. This is why I prefer a parallel branch. :(

**Comment by lowjoel** [comment]
I don't think there's a need to use constexpr in most of the places I replaced it with const. The only difference is for the constexpr with float, and even then we can still separate them with constant floats defined in the .cpp. There's no constexpr functions, which I think is a significant change.

**Comment by rkhaotix** [comment]
I agree in parts! :)
But it's ok... I really want to include your changes in the code base... 
May I ask you one thing? Do you can merge your changes in the branch "cli-changes" and redo the pull request? The mentioned branch is the most updated with several fixes that will come to 0.8.1-alpha.

**Comment by lowjoel** [comment]
Okay, I'll do that when I get home.

**Comment by rkhaotix** [comment]
Thank you so much! I am preparing a panel in the about dialog and include the name of the main contributors and for sure yours will be there! ;)

**Pull request closed without merging**
