### PR TITLE
 Allow pgmodeler to be compiled with Visual Studio (Take 3)

### PR DESCRIPTION
**Pull request by lowjoel**
See #653 and #654.

I think I'm going blind.

### CODE REVIEW

**Comment by lowjoel** [comment]
@rkhaotix hopefully I did it right this time...

**Comment by lowjoel** [comment]
@rkhaotix hang on, there's some other changes.

**Comment by lowjoel** [comment]
@rkhaotix Okay, fixed it. There's two new commits at the back, modifying the project files. These define constants for MSVC (__PRETTY_FUNCTION__ is a GCC extension) and also a constant to disable the secure C library warnings.

There's also another fix which allows paths with spaces to be used on Windows.

It should not break the compile, but let me know if it does...

**Comment by rkhaotix** [comment]
Ok. I'll fix the build in all support platforms and let you know! Thanks again!

**Comment by rkhaotix** [comment]
@lowjoel I'm having issues trying to compile your cli-changes branch...Linker says: "LINK : fatal error LNK1104: cannot open file 'utils.lib'"

I'm using Qt 5.4.1 MSVC 2013 OpenGL, Visual Studio Community 2013, PostgreSQL 9.4.1 all for 64bits.

vs2013

**Comment by rkhaotix** [comment]
@lowjoel  Ignore my last comment... My fault! ¬¬'

**Comment by rkhaotix** [comment]
@lowjoel How did manage to compile pgModeler using MSVC since libxml2 is compiled for using in MingW? I've tried to compile it (libiconv and libxml2) by myself on msvc but no success... **Scratching my head** :S

**Comment by rkhaotix** [comment]
@lowjoel Finally I've managed to compile pgModeler using visual studio. Also confirmed that the process runs flawlessly in Linux (openSuse + clang) and Mac OSX (Mavericks + clang)! 

I think we can merge your changes! Thanks!

**Comment by lowjoel** [comment]
@rkhaotix Yay! libiconv and libxml2 is hard to compile on Windows with VS but possible. I compiled Ruby using VS :)

I'll use pgmodeler for a while, and see if I can find any other problems. I'll fix the warnings over time.

The size_t => unsigned data loss conversion is a 64-bit compile warning. I'll also fix that over time.

**Comment by lowjoel** [comment]
@rkhaotix I also got the error of missing 'utils.lib' when compiling for Release for the first time. I think it's because the builds run in parallel; there's no dependency among projects.

**Comment by rkhaotix** [comment]
The problem with 'utils.lib' is that you are trying to use "Shadow build"... In QtCreator disable this option in "Build" section of the project. This will solve!

I've manage to use the same libiconv and libxml2 that cames bundled with PostgreSQL... Compilation works like a charm! :)

The only thing I need to solve is the warnings...

**Comment by lowjoel** [comment]
*facepalm yes I remembered changing that for debug, forgot to change that for release.

**Comment by rkhaotix** [comment]
I'm still fighting with the C4267 warning (sizet_t conversion to unsigned/int)...

The problem is: pgModeler initially was designed to be a tool only for Linux so I coded the most of it using unsigned that is in fact the same as size_t in that OS.. I left the implicit cast to compiler (maybe a mistake!). In Mac OSX too, size_t and unsigned has the same size in bits (32)... if my memory serves.

But I discovered a bit late (today! :p) that size_t is different from unsigned in Windows! One is 64 bits and the second 32 bits. 

Analyzing the code I discovered that the majority of the warnings come from assignments like this: 
<code>value=stl_container.size()</code> where <code>value</code> is an unsigned.

Others came from operations like this: <code>value=stl_container.size() - number</code> where <code>value</code> is an unsigned too. Again, I relied in the implicit casts from Linux compilers.. :/

But I think the fix moving unsigned to size_t may bring bugs because the same unsigned variable is used in several line in the same method. Now I'm kinda frustrated about that! :(

For now the warning is just disabled but I know that the application can explode due to integer overflow anytime depending upon on how huge a the model being designed! :(

**Comment by lowjoel** [comment]
It's mostly harmless unless we have > 4 billion records. We should fix it, but until then, it should be fine. It's different only because we're using a 64-bit compiler.

Moving from unsigned to size_t should be the correct move, since size_t is what we use for all the container sizes... both are unsigned, and on Linux size_t is unsigned int, on Windows size_t is unsigned long long (or unsigned int, depending on compiler)

Why would moving to size_t introduce bugs?

**Comment by rkhaotix** [comment]
It's just a silly fear! Forget it... :)
The only thing I know is that the work will be huge. To give an idea the compiler generates over 145 C4267 warnings! 

But gradually we will get rid of them! Thanks again for your support!

**Comment by lowjoel** [comment]
Haha, I feel you. It's scary when we try to change something big.

I'll slowly fix the warnings and PR when they're mostly gone. It's okay, at least now we can build on Windows/VC :)

I'll be integrating pgmodeler into my workflow (moving from MySQL to Postgres, so MySQL Workbench to pgmodeler!) I'll see if I need anything. I might implement a feature in future, who knows :stuck_out_tongue:

**Comment by rkhaotix** [comment]
Wow, that's the spirit! 
I'll be waiting your PR with the warning fixes and YOUR OWN NEW FEATURE! ;)

**Comment by lowjoel** [comment]
Haha thanks. I was looking for something like pgmodeler for a while now, contributing to it is the least I can do. Cheers for writing such a tool!

**Comment by rkhaotix** [comment]
@lowjoel I was thinking on a solution to the C4267 and found some interesting (and annoying!) things:

1) I was wrong when I said that ```size_t``` is the same as ```unsigned``` in Linux. The first one is twice the size of the latter.

2) I discovered that Qt (in Linux and Mac OSX) was hiding the warning ```-Wshorten-64-to-32``` which basically means that I was not able to see the problem with assignment of the  ```size_t```  to ```unsigned``` from the very beginning of project's development. When I forcibly activated the warning, for my surprise, even classes in the Qt framework suffers from the problem!

3) I was thinking a lot about the real need to convert any ```unsigned``` to ```size_t``` where the warnings are pointing. I came to conclusion that it may be a bit overkill for 64 bit systems. We have a lot of loops and assignments that uses (until now) 32 bit integers and switch them to a 64 bit integer  can lead to an unnecessary overuse of processor/memory.

Well, I didn't resisted to temptation to try some hacks. :)

The first one was basically replace the unsigned by size_t... I gave up in the middle of the process because a lot of code was changed and that fear raised again! The current code is in branch ````sizet-usage````:p

In a second try, I created a macro called ```__cast_uint``` that in 64 bit systems is replaced by a ```static_cast<unsigned>``` and in 32 bit ones has no effect and placed at points the compiler complains. As far as I know the ```static_cast``` works in compile time, so I could get rid of the warnings on all systems changing a bit o lines (almost 100). The downside of this hack is that we will have to use the macro every time we have a statement like this: ```unsigned var=container.size()```. But the advantage is that we'll be always using 32bit integers in the operations. :)

I've pushed the changes to the branch ```warnings-removal``` for your appreciation. What do you think? Suggestions?

The only thing I just won't is to force the compiler to silence the warnings, not anymore! :)

**Comment by lowjoel** [comment]
I think we should have a separate ticket for this!

I think the best solution is to drop iteration over integers altogether. A lot of the iteration is used over a container, so we should be using ranged-based for loops (or, at worst, using begin() and end())

There was even a std::map of unsigned :open_mouth: 

I don't think that casting the 64- to 32-bit integer will be any faster on 64-bit CPUs, since both will compute any arithmetic operation in 1 clock cycle...

**Comment by rkhaotix** [comment]
> I think we should have a separate ticket for this!

Agreed! :)

>
> I think the best solution is to drop iteration over integers altogether.
A lot of the iteration is used over a container, so we should be using
ranged-based for loops (or, at worst, using begin() and end())

This will be a huge task. But let's discuss the better approach. I know
that there are a lot of design problems in the code, when I started to
write pgModeler I barely known about C++ and Qt. But today with all
knowledge I've gained I could rewrite pgModeler using best practices but
this is quite impossible to do alone. Almost 80k lines (in the last time I
counted)..imagine start all over again. :(

>
> There was even a std::map of unsigned

Yes, I have some maps which keys are integers because in some operations i
need to handle objects by their id in a sorted way... What I like in map is
that as I add elements in it it will sort elements by key. Maybe there must
be some other weird structure nothing that can't be changed.. It's not why
I wrote the algorithm that it is the best solution.  Many users pushed or
suggested some interesting ones, like you've done.

> I don't think that casting the 64- to 32-bit integer will be any faster
on 64-bit CPUs, since both will compute any arithmetic operation in 1 clock
cycle...
>

I don't mean speed when talking about 64bit integers but memory usage, or
in a low level, register usage.

**Pull request merged**
